In [4]:
import math
import pandas as pd
import numpy as np

In [8]:
experiment_num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

v = [133.98,134.35,134.91,169.50,174.49,180.12,188.68,217.24,240.00,240.00]
f = [0.708,0.704,0.698,0.442,0.417,0.393,0.357,0.269,0.168,0.114]
d = [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]
t_m = [3,3,3,4,4, 4,5,5,8,11]
SR = [2.43,2.41,2.38,1.20,1.10, 1.00,0.87,0.57,0.34,0.25]

table = pd.DataFrame()
table["Experiment_Num"] = experiment_num
table["v"] = v
table["f"] = f
table["d"] = d
table["t_m"] = t_m
table["SR"] = SR
table

   Experiment_Num       v      f    d  t_m    SR
0               1  133.98  0.708  1.5    3  2.43
1               2  134.35  0.704  1.5    3  2.41
2               3  134.91  0.698  1.5    3  2.38
3               4  169.50  0.442  1.5    4  1.20
4               5  174.49  0.417  1.5    4  1.10
5               6  180.12  0.393  1.5    4  1.00
6               7  188.68  0.357  1.5    5  0.87
7               8  217.24  0.269  1.5    5  0.57
8               9  240.00  0.168  1.5    8  0.34
9              10  240.00  0.114  1.5   11  0.25

In [ ]:
def machining_time(D = 38, L = 55, v, f){
    return math.pi * D  * L / (1000 * 10000 * v * f)
}
v_min = 50
v_max = 240
f_min = 0.062
f_max = 0.0762

In [ ]:
# Jaya algorithm 
num_iterations = 1000
generations = 100
population_size = 1000